

services:
  backend:
    build: ./site_sae
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USERNAME=${{ secrets.DB_USERNAME }}
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
    depends_on:
      - db


  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_cpn_prod
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_USER: ${{ secrets.DB_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
    volumes:
      - ./db_prod_data:/var/lib/mysql
    ports:
      - "3306:3306"
