services:
  site:
    build: ./site_sae
    container_name: site_cpn_dev
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db_cpn_dev
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db_cpn_dev
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: db_cpn_dev
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_dev_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cpn_dev
    environment:
      PMA_HOST: db_cpn_dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube_cpn_dev
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db_cpn_dev:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
      - SONARQUBE_JDBC_USERNAME=user
      - SONARQUBE_JDBC_PASSWORD=password
    depends_on:
      - db
