services:
  site:
    build: ./site_sae
    container_name: site_cpn_dev
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db_cpn_dev
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: db_cpn_dev
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: db_cpn_dev
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_dev_data:/var/lib/mysql
    ports:
      - "3306:3306"
    user: "${UID}:${GID}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cpn_dev
    environment:
      PMA_HOST: db_cpn_dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
